# Site settings
baseURL = "//edenvicary.com"
languageCode = "en-US"
title = "Eden Vicary - Software Engineer"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-130572769-1"

# Copyright
copyright = "&copy;2018 Eden Vicary"

[params]

  # Metadata for search engines and social sharing
  author = "Eden Vicary"
  description = "I’m curious about how we can build tools to help people’s work lives be as effective and fun as possible!"
  shareImage = "eden_wedding.jpg"
  twitterHandle = "edenvicary"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "eden_conversation.jpg"
      position = "center center"

  [[params.links]]
    [params.links.list1]
      heading = "Work"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/edenvicary/"

      [[params.links.list1.link]]
        text = "GitHub"
        url = "https://github.com/edenvicary"

      [[params.links.list1.link]]
        text = "Medium"
        url = "https://medium.com/@edenvicary"

  [[params.links]]
    [params.links.list2]
      heading = "Personal"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/edenvicary/"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/edenvicary"

      [[params.links.list2.link]]
        text = "Bible"
        url = "https://my.bible.com/users/Edovic"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
